version: '3.3'
services:
    thumborContainer:
        # image: minimalcompact/thumbor:7.0.0
        image: apsl/thumbor
        container_name: thumbor
        env_file:
            - .env
        ports:
            - '8000:8000'
        volumes:
            - thumbor-data:/data/asset
volumes: 
    thumbor-data: